version: "2"
services:
  boilerplate-api:
    build: .
    environment:
      # SQL URI
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
